-- PROMEDIAR NIVEL DE CONFIANZA PIEZA DE INTELIGENCIA

CREATE OR REPLACE PROCEDURE P_NIVEL_CONF_PZ (
    ID_HC IN NUMBER,
    ID_PI IN NUMBER
) 
IS 
    ID_PI_SELECT NUMBER; 
    ID_HC_SELECT NUMBER;  
BEGIN

    IF ((ID_HC IS NULL) OR (ID_PI IS NULL)) THEN
        RAISE_APPLICATION_ERROR(-20001, 'A OCURRIDO UN ERROR AL INSERTAR - ' || SQLCODE || ' -ERROR- ' || SQLERRM);    
    ELSE
        SELECT id INTO ID_PI_SELECT FROM pieza_inteligencia WHERE id = ID_PI;
        SELECT id_hecho_cdo INTO ID_HC_SELECT FROM hecho_crudo WHERE id_hecho_cdo = ID_HC;

        INSERT INTO p_h VALUES (ID_HC_SELECT, ID_PI_SELECT);

        -- SACAR PROMEDIO AQUI
        
    END IF;

    COMMIT;

    EXCEPTION WHEN OTHERS THEN  
        RAISE_APPLICATION_ERROR(-20001, 'A OCURRIDO UN ERROR AL INSERTAR - ' || SQLCODE || ' -ERROR- ' || SQLERRM);
END;


-- USAR PROCEDURE P_NIVEL_CONF_PZ
BEGIN
   P_NIVEL_CONF_PZ (#,#); -- # ES EL ID DEL HC Y LA PI
   COMMIT;
END;